# Textbook Component Contracts
# Defines the interface specifications for reusable components in the textbook

openapi: 3.0.0
info:
  title: Physical AI Textbook Components API
  description: Defines the interface specifications for reusable MDX components in the Physical AI & Humanoid Robotics textbook
  version: 1.0.0

components:
  schemas:
    CodeExample:
      type: object
      required:
        - title
        - language
        - code
        - description
      properties:
        title:
          type: string
          description: Title of the code example
        language:
          type: string
          description: Programming language or format (python, bash, xml, etc.)
        code:
          type: string
          description: The actual code content
        description:
          type: string
          description: Explanation of what the code does
        environment:
          type: string
          description: Target environment for execution
        executionInstructions:
          type: string
          description: Step-by-step instructions to run the code

    Exercise:
      type: object
      required:
        - title
        - description
        - difficulty
        - type
      properties:
        title:
          type: string
          description: Title of the exercise
        description:
          type: string
          description: Detailed description of the exercise
        difficulty:
          type: string
          enum: [beginner, intermediate, advanced]
          description: Difficulty level
        type:
          type: string
          enum: [theoretical, practical, coding, analysis]
          description: Type of exercise
        solution:
          type: string
          description: Solution or expected outcome
        hints:
          type: array
          items:
            type: string
          description: Helpful hints for solving the exercise

    Diagram:
      type: object
      required:
        - title
        - type
        - description
      properties:
        title:
          type: string
          description: Title of the diagram
        type:
          type: string
          enum: [mermaid, conceptual, 3d-model]
          description: Type of diagram
        description:
          type: string
          description: Textual description of the diagram content
        content:
          type: string
          description: Mermaid syntax or description of the diagram
        imageUrl:
          type: string
          description: Path to static image if applicable

    GlossaryTerm:
      type: object
      required:
        - term
        - definition
      properties:
        term:
          type: string
          description: The technical term
        definition:
          type: string
          description: Definition of the term
        usageExamples:
          type: array
          items:
            type: string
          description: Examples of how the term is used
        relatedTerms:
          type: array
          items:
            type: string
          description: Related terms in the glossary

    LearningOutcome:
      type: object
      required:
        - statement
        - measurable
      properties:
        statement:
          type: string
          description: The learning outcome statement
        measurable:
          type: boolean
          description: Whether the outcome is measurable
        assessmentMethod:
          type: string
          description: How the outcome will be assessed

    ChapterMetadata:
      type: object
      required:
        - title
        - description
        - learningOutcomes
      properties:
        title:
          type: string
          description: Title of the chapter
        description:
          type: string
          description: Brief description of the chapter content
        learningOutcomes:
          type: array
          items:
            $ref: '#/components/schemas/LearningOutcome'
          description: List of learning outcomes for the chapter
        prerequisites:
          type: array
          items:
            type: string
          description: Prerequisite chapters or concepts
        dependencies:
          type: array
          items:
            type: string
          description: Chapters that depend on this one
        duration:
          type: number
          description: Estimated time to complete in hours