"""Data model for a vector embedding."""

from datetime import datetime
from typing import Dict, Any, List
from dataclasses import dataclass


@dataclass
class VectorEmbedding:
    """
    A numerical representation of content chunk generated by Cohere models
    that enables semantic similarity search.
    """

    chunk_id: str  # Reference to the associated BookContentChunk
    vector: List[float]  # The embedding vector (typically 768 dimensions)
    model_name: str  # Name of the model used to generate the embedding
    model_version: str  # Version of the model used
    created_at: datetime  # Timestamp when embedding was generated

    def __post_init__(self):
        """Validate the embedding after initialization."""
        if not self.chunk_id.strip():
            raise ValueError("chunk_id must be valid")
        if not self.vector:
            raise ValueError("vector must not be empty")
        if len(self.vector) == 0:
            raise ValueError("vector must have at least one dimension")
        if not self.model_name.strip():
            raise ValueError("model_name must be valid")
        if not self.model_version.strip():
            raise ValueError("model_version must be valid")

    @classmethod
    def create_from_vector(
        cls,
        chunk_id: str,
        vector: List[float],
        model_name: str = "embed-multilingual-v2.0",
        model_version: str = "2.0",
    ) -> "VectorEmbedding":
        """
        Create a VectorEmbedding from a vector with automatic timestamp.

        Args:
            chunk_id: Reference to the associated BookContentChunk
            vector: The embedding vector
            model_name: Name of the model used to generate the embedding
            model_version: Version of the model used

        Returns:
            VectorEmbedding instance
        """
        return cls(
            chunk_id=chunk_id,
            vector=vector,
            model_name=model_name,
            model_version=model_version,
            created_at=datetime.now(),
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert the embedding to a dictionary representation."""
        return {
            "chunk_id": self.chunk_id,
            "vector": self.vector,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VectorEmbedding":
        """Create a VectorEmbedding from a dictionary representation."""
        return cls(
            chunk_id=data["chunk_id"],
            vector=data["vector"],
            model_name=data["model_name"],
            model_version=data["model_version"],
            created_at=datetime.fromisoformat(data["created_at"]),
        )